### ISSUE TITLE
Different VMAF result with the latest versions of ab-av1

### ISSUE THREAD

**Issue by Werve** [alexheretic/ab-av1#238] opened 2024-11-18 10:14 UTC
I upgraded from an old version (I think it was the 0.7.12) to 0.8.0 and noticed strange results in my usual workflow so I went deeper and ran a test using the same command and file again:
ab-av1 vmaf --reference “**_pathfile1_**” --distorted “**_pathfile2_**”

Using ab-av1 0.8.0 the result is:
`39.40909`

Using ab-av1 0.8.0 and `--vmaf ts_sync_mode=default` the result is:
`41.911076`

Using ab-av1 0.7.19 the result is:
`39.40909`

Using ab-av1 0.7.12 the result is:
`97.80562`

Using ab-av1 0.7.15 the result is:
`97.80562`

Using ab-av1 0.7.17 the result is:
`39.40909`

Using FFMetrics 1.5b13 (that detect ffmpeg 6.1.1 in path):
Mean: `97.805618`

Using MSU VQMT Free 14.1 (with the 0.6.1 vmaf model setting and cubic upscale to 1920x1080 just in case):
Mean: `97.436417`

Since two external tools report a much higher vmaf I think there is an error with the latest versions of ab-av1, or is it an intended result?

Also i noticed that the 2 video files used have different duration, so i will manually compare frames to figure out better (not ab-av1 fault).

**Comment by alexheretic** [comment] 2024-11-18 10:51
This is most likely related to #215 which was released with v0.7.17.

You could try running with [debug logging](https://github.com/alexheretic/ab-av1?tab=readme-ov-file#debug) to see the ffmpeg call and reproduce calling ffmpeg directly. Then modify the vmaf args to see what impacts the analysis here.

**Comment by Werve** [comment] 2024-11-18 11:26
I enabled debug logging and saw ab-av1 0.8.0 makes a call like this:
ffmpeg -i **_filepath2_** -i **_filepath1_** -filter_complex [0:v]format=yuv420p10le,setpts=PTS-STARTPTS,settb=AVTB[dis];[1:v]format=yuv420p10le,setpts=PTS-STARTPTS,settb=AVTB[ref];[dis][ref]libvmaf=shortest=true:ts_sync_mode=nearest:n_threads=8 -f null -

FFMetric makes a call like this:
ffmpeg -hide_banner -nostdin -r 25 -i "**_filepath2_**" -r 25 -i "_**filepath1**_" -lavfi "[0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:log_fmt=json:log_path='C\:/Users/A/AppData/Local/Temp/FFMetrics/db2f3e36-90a1-4d80-a169-5d20264015eb.log':n_threads=7:pool=Harmonic Mean:model=version=vmaf_v0.6.1" -f null -

So i tried re-adding -r 25 before inputs of the ab-av1 ffmpeg call and the vmaf result is the same of the previous versions:
`97.805618`

But I don't know if this is really the correct case. 
I will look at the frames manually to see if the quality is really good.

**Comment by alexheretic** [comment] 2024-11-18 13:23
Interesting as we used to use `-r 24` until that pr. Do you mind sharing the ffprobe, or part of it, for the two videos? 

I think we removed it because the justifications for it were dubious. But if we have a good case for it maybe we can restore it, or add it as an option etc.

**Comment by Werve** [comment] 2024-11-18 20:25
ffprobe of the source/reference file:

```
ffprobe version 6.1.1-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\Videos\test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2011-04-05T18:53:57.000000Z
  Duration: 00:01:30.48, start: 0.000000, bitrate: 4620 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 4465 kb/s, 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      creation_time   : 1970-01-01T00:00:00.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 149 kb/s (default)
    Metadata:
      creation_time   : 2011-04-05T18:53:58.000000Z
      vendor_id       : [0][0][0][0]
```

ffprobe of the distorted/encoded file:
```
ffprobe version 6.1.1-full_build-www.gyan.dev Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[libdav1d @ 000002dcbe803f00] libdav1d 1.3.0-22-g746ab8b
Input #0, matroska,webm, from 'E:\Videos\test2.mkv':
  Metadata:
    COMPATIBLE_BRANDS: isommp42
    creation_time   : 2011-04-05T18:53:57.000000Z
    MAJOR_BRAND     : mp42
    MINOR_VERSION   : 0
    ENCODER         : Lavf60.3.100
  Duration: 00:01:30.83, start: 0.000000, bitrate: 3122 kb/s
  Stream #0:0: Video: av1 (Main), yuv420p10le(tv, progressive), 1920x1080, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn
    Metadata:
      BPS             : 1556010
      NUMBER_OF_FRAMES: 199
      NUMBER_OF_BYTES : 1548230
      _STATISTICS_WRITING_APP: mkvmerge v79.0 ('Funeral Pyres') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2023-09-14 18:51:16
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      ENCODER         : Lavc60.3.100 av1_nvenc
      DURATION        : 00:01:30.826000000
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:01:30.418000000
[libdav1d @ 000002dcbe881d40] libdav1d 1.3.0-22-g746ab8b
```


For clarity, the encoded file is the result of merging several segments via mkvmerge.

**Comment by Werve** [comment] 2024-11-18 23:20
I compared several frames where the VQMT tool reported worse vmaf values with the reference file and the quality is not as bad as one might think with a value of 39-40 as ab-av1 0.8.0 reports (thus without the -r argument). 
If I had to compare subjectively from various vmaf values viewed in various experiments it seems to me throughout the video in line with 90+ values

**Comment by alexheretic** [comment] 2024-11-23 15:05
So I think the answer is to re-introduce the `-r FPS` flag for vmaf. But what do we set it to? Perhaps the reference fps reported by ffprobe. And do we always set it, or only if there is some mismatch detected? In this case the probe output looks about the same for ref/distorted.

Also is there some public example we can add as a test case for this to avoid future regressions?

**Comment by mr44er** [comment] 2024-11-23 15:46
I don't like that idea. I mean, if you input a "broken" source file (I really see variable fps as broken or at least indecent), it is not VMAF's fault if different frames at the same time are compared.

> In this case the probe output looks about the same for ref/distorted.
That is another problem, ffmpeg and ffprobe don't show the real framerate without an explicit search.

The other problem is that the encoded video with -r 24 is still wrong. Test programs for VMAF will still complain about it afterwards because it was not encoded properly.

ab-av1 should not represent a workaround in itself, but at most offer one optionally for such cases. I personally fix such cases by first converting the file with the correct **constant** fps (which is rarely "true" 24, some german or french movies have it), but you should need to know the correct one. If choosing/guessing the wrong one, VMAF calculation will work, but the playtime will differ from the "real" original, because the total frames differ.

If you want to optionally add a workaround (let's call it `--vfr-workaround`), you can't cover all cases without carefully inspecting the source file. Assuming that you only want to guarantee the correct VMAF calculation, you can do the following: 
Convert the file with the fps-filter into x264lossless,x265lossless,ffv1, doesn't matter all are fast and produce nearly same file size  `-vcodec ffv1 -level 3 -vf "fps=fps=24" -an -sn -dn tempoutfix.mkv` and give this file als input to VMAF.

**Comment by Werve** [comment] 2024-11-25 10:09
> Check your files with `mediainfo -f test.mp4`
> 
> Keep an eye out for:
> 
> ```
> Frame rate mode                          : CFR
> Frame rate mode                          : Constant
> Frame rate                               : 25.000
> Frame rate                               : 25.000 FPS
> FrameRate_Num                            : 25
> ```
> 
> If there are differences/variable framerate, this is the culprit.

I report some mediainfo output for more context.

About the **reference** file:
```
Format                      : MPEG-4
Format profile              : Base Media / Version 2
Codec ID                    : mp42 (isom/mp42)
File size                   : 49.8 MiB
Duration                    : 1 min 30 s
Overall bit rate mode       : Variable
Overall bit rate            : 4 621 kb/s
Frame rate                  : 25.000 FPS
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4
Format settings             : CABAC / 1 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 1 frame
Format settings, GOP        : M=1, N=25
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 1 min 30 s
Bit rate                    : 4 466 kb/s
Maximum bit rate            : 12.9 Mb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 25.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.086
Stream size                 : 48.2 MiB (97%)
Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 1 min 30 s
Bit rate mode               : Variable
Bit rate                    : 150 kb/s
Maximum bit rate            : 219 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 1.62 MiB (3%)
```

About the **distorted** file:
```
Format                      : Matroska
Format version              : Version 4
File size                   : 33.8 MiB
Duration                    : 1 min 30 s
Overall bit rate            : 3 122 kb/s
Frame rate                  : 2.191 FPS
Video
ID                          : 1
Format                      : AV1
Format/Info                 : AOMedia Video 1
Format profile              : Main@L4.0
Codec ID                    : V_AV1
Duration                    : 1 min 30 s
Bit rate                    : 1 556 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Variable
Frame rate                  : 2.191 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.342
Stream size                 : 1.48 MiB (4%)
Writing library             : Lavc60.3.100 av1_nvenc
Default                     : No
Forced                      : No
Color range                 : Limited

Audio
ID                          : 2
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : A_AAC-2
Duration                    : 1 min 30 s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
```

**Comment by mr44er** [comment] 2024-11-25 16:04
Ugh, that's even worse if your distorted file comes out with variable fps and `Frame rate                  : 2.191 FPS` is definitely wrong. This shouldn't be the case if the reference file _really_ has CFR.

There is something wrong with the reference file, I suspect either a broken header if mediainfo doesn't show it or it is generally corrupt.

Try this (it writes out the file as lossless into ffmpeg-codec, filtered as 25fps, strips off audio, so only video):
`ffmpeg -i reference.mp4 -vcodec ffv1 -level 3 -vf "fps=fps=25" -an -sn -dn reference_25fpsfiltered_lossless.mp4`

Try again with `reference_25fpsfiltered_lossless.mp4` and compare results (also again mediainfo afterwards).

**Comment by Werve** [comment] 2024-11-25 18:51
I tried with
`ffmpeg -i reference.mp4 -vcodec ffv1 -level 3 -vf "fps=fps=25" -an -sn -dn reference_25fpsfiltered_lossless.mp4`
but actually it show errors:
```
[mp4 @ 0000022c5afd7040] Could not find tag for codec ffv1 in stream #0, codec not currently supported in container
[out#0/mp4 @ 0000022c5a71eb80] Could not write header (incorrect codec parameters ?): Invalid argument
[vf#0:0 @ 0000022c5a6acb80] Error sending frames to consumers: Invalid argument
[vf#0:0 @ 0000022c5a6acb80] Task finished with error code: -22 (Invalid argument)
[vf#0:0 @ 0000022c5a6acb80] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 0000022c5a71eb80] Nothing was written into output file, because at least one of its streams received no packets.
```
But
`ffmpeg -i reference.mp4 -vcodec ffv1 -level 3 -vf "fps=fps=25" -an -sn -dn reference_25fpsfiltered_lossless`**.mkv**
Works.

So using `ffmpeg -i distorted.mkv -i reference_25fpsfiltered_lossless.mkv -filter_complex [0:v]format=yuv420p10le,setpts=PTS-STARTPTS,settb=AVTB[dis];[1:v]format=yuv420p10le,setpts=PTS-STARTPTS,settb=AVTB[ref];[dis][ref]libvmaf=shortest=true:ts_sync_mode=nearest:n_threads=8 -f null -`

The output is:
```
[Parsed_libvmaf_6 @ 00000265815ddfc0] VMAF score: 37.938792e=N/A speed=0.565x
[out#0/null @ 00000265fef97b80] video:972KiB audio:15576KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame= 2262 fps= 14 q=-0.0 Lsize=N/A time=00:01:30.41 bitrate=N/A speed=0.565x
```

So still a low VMAF value instead of a 90+

I think something in the merging with mkvmerge set the wrong frame length and fps. (distorted file)

**Comment by Werve** [comment] 2024-11-25 19:11
Also with:
`ffmpeg -i reference_25fpsfiltered_lossless.mkv -i distorted_25fpsfiltered_lossless.mkv -filter_complex [0:v]format=yuv420p10le,setpts=PTS-STARTPTS,settb=AVTB[dis];[1:v]format=yuv420p10le,setpts=PTS-STARTPTS,settb=AVTB[ref];[dis][ref]libvmaf=shortest=true:ts_sync_mode=nearest:n_threads=8 -f null -`

It output the same:
```
[Parsed_libvmaf_6 @ 0000028a2ea360c0] VMAF score: 37.932722e=N/A speed=0.415x
[out#0/null @ 0000028a2dedcc00] video:972KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame= 2262 fps= 10 q=-0.0 Lsize=N/A time=00:01:30.44 bitrate=N/A speed=0.415x
```

**Comment by mr44er** [comment] 2024-11-25 19:29
> But
> `ffmpeg -i reference.mp4 -vcodec ffv1 -level 3 -vf "fps=fps=25" -an -sn -dn reference_25fpsfiltered_lossless`**.mkv**
> Works

Yeah, sorry my bad...ffv isn't compatible with mp4. mkv is the correct solution.

I meant repeat the encoding with ab-av1 with this file. (to create a "good" distorted file)

**Comment by Werve** [comment] 2024-11-27 10:57
> I meant repeat the encoding with ab-av1 with this file. (to create a "good" distorted file)

Using ab-av1 0.8.0 and creating a distorted file with the following command (without forcing fps):
`ab-av1 auto-encode -i reference.mp4 -o distorted.mkv -e av1_nvenc`
It finished the encoding with output:
`00:02:56 crf 39 1/1 ########################################################################### (VMAF 95.39, size 36%)  00:00:11 Encoding ################################################################################## (215 fps, eta 0s)Encoded 18.16 MiB (36%)`

Then I compared the VMAF value between the file reference.mp4 and this distorted.mkv
Using ab-av1 0.8.0 `ab-av1 vmaf --reference reference.mp4 --distorted distorted.mkv`
Output:
```
00:03:46 ####################################################################################### (vmaf 10 fps, eta 0s)
95.37866
```
Using VQMT 14.1 Free (vmaf model 061):
The mean VMAF is `94.978012`

Therefore, it aligns with the comparison result obtained from ab-av1/ffmpeg.
So, as I hypothesized, there seems to be no problem with the input file, but with that particular encoded (distorted) file that I mentioned at the beginning.

**Comment by VoroxThund** [comment] 2024-12-14 21:14
I encounter same problem too

ffmpeg and ab-av1 show completely different scores, and I believe ffmpeg giving the right one
ffmpeg 98.612468
ab-av1 74.52522

Here's file:
[https://www.mediafire.com/file/c8zbu5piw0lzpy8/Transcode.zip/file](https://www.mediafire.com/file/c8zbu5piw0lzpy8/Transcode.zip/file)

And here's how to reproduce this:

Run this to generate distorted file
`ffmpeg -i ref5.flv -y -c:a copy -c:v libsvtav1 -preset 4 -crf 18 -keyint_min 150 -svtav1-params fast-decode=1 -svtav1-params tune=0 -benchmark ref5_crf_18.mp4`

Run this to calculate VMAF score in ffmpeg
```
ffmpeg -r 24 -i ref5_crf_18.mp4 -r 24 -i ref5.flv -lavfi libvmaf="n_threads=4" -f null -
VMAF score: 98.612468
```

Run this to calculate VMAF score in ab-av1
```
RUST_LOG=ab_av1=debug ab-av1 vmaf --reference ref5.flv --distorted ref5_crf_18.mp4
⠁ 00:00:00 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- (vmaf running, eta 0s)[2024-12-14T20:47:55Z INFO  ab_av1::vmaf] vmaf ref5_crf_18.mp4 vs reference ref5.flv
[2024-12-14T20:47:55Z DEBUG ab_av1::vmaf] cmd `ffmpeg -i ref5_crf_18.mp4 -i ref5.flv -filter_complex [0:v]format=yuv444p10le,setpts=PTS-STARTPTS,settb=AVTB[dis];[1:v]format=yuv444p10le,setpts=PTS-STARTPTS,settb=AVTB[ref];[dis][ref]libvmaf=shortest=true:ts_sync_mode=nearest:n_threads=4 -f null -`
  00:00:12 ############################################################################################################################################################################################################ (vmaf 37 fps, eta 0s)
74.52522
```

After adding -r 24 to the ffmpeg command ab-av1 generated, everything seems fine now
```
ffmpeg -r 24 -i ref5_crf_18.mp4 -r 24 -i ref5.flv -filter_complex "[0:v]format=yuv444p10le,setpts=PTS-STARTPTS,settb=AVTB[dis];[1:v]format=yuv444p10le,setpts=PTS-STARTPTS,settb=AVTB[ref];[dis][ref]libvmaf=shortest=true:ts_sync_mode=nearest:n_threads=4" -f null -
VMAF score: 98.612468
```

My question is that how can I adding -r 24 in version v0.8.0, is it possible?
Or I have to fork and modify code?

**Comment by mr44er** [comment] 2024-12-15 05:39
> seems fine

And only that. ;)

Can you try for fun what happens if you use `-r 25` (PAL), `-r 23.976` (ntsc-film) and `-r 29.970` (ntsc)?

**Comment by VoroxThund** [comment] 2024-12-15 06:11
-r 25 (PAL), -r 23.976 (ntsc-film) and -r 29.970 (ntsc)
All gives same VMAF score: 98.612468

**Comment by mr44er** [comment] 2024-12-15 07:36
Yep, that's exactly what my playing around with this problem has revealed. Any fixed fps rate results in a correct vmaf calculation but it distorts the resulting video and so simply always using -r 24 would definitely not be a good idea or even a workaround.

**Comment by alexheretic** [comment] 2024-12-22 10:11
#250 I've added `--vmaf-fps` arg for setting `-r`. This allows setting the value to workaround this issue.

I'm not sure I understand the downside of defaulting this again to 24 (or 25 or whatever), since that used to work ok afaik. For my test videos I think 24/25 or no explicit value works fine. Is there a downside to defaulting vmaf fps?

**Closed** 2024-12-23 20:43 UTC

**Comment by alexheretic** [comment] 2024-12-23 20:44
I'll have the next version default `--vmaf-fps 25` since it fixes this issue and I know of no downsides.

This behaviour can be disabled by setting `--vmaf-fps 0`.

**Comment by mr44er** [comment] 2025-01-06 15:53
Unfortunately, I was away for a while, but I will report back if I notice anything during the tests. (I haven't had a chance to do anything in the last few weeks).

**Comment by Werve** [comment] 2025-01-11 09:13
I recently had a chance to work on the methodology I had used to create the distorted file that had the problem described at the beginning, so using mediainfo it show an incorrect FPS value.

I was able to create another file with the same problem of incorrect FPS shown in this way:
- Splitting a video input into several segments with mkvmerge/toolnix (without re-encoding)
- Encode each resulting segment with (for example) ab-av1
- Rejoin the segments with FFMPEG concat

In particular, I noticed that the problem arises with the last step, using ffmpeg to merge the video files, and does not occur if you use mkvmerge instead 

However I used ab-av1 version 0.9.0 and now the VMAF values are as expected.

**Comment by mr44er** [comment] 2025-02-01 06:14
> I'm not sure I understand the downside of defaulting this again to 24 (or 25 or whatever), since that used to work ok afaik. For my test videos I think 24/25 or no explicit value works fine. Is there a downside to defaulting vmaf fps?

Seems I missed an answer here. As long as the forced fps (really it doesn't matter which ones) are only used for the VMAF calculation, that's fine.

It just shouldn't be included in the encoding process. (...which you have implemented correctly)
